auto: true
pygments: true
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /posts/:title
url: http://metapolator.com
production_url : http://metapolator.com
title: Metapolator
subtitle: Design font families
description: Metapolator is a web-based parametric font editor for designing families
# disqus_shortname: metapolator_blog
# analytics: UA-12312312-3
# gauges: 50f2b533613f5d7c8000000d
author :
  name : Metapolator
  github : metapolator
  twitter : metapolator
  email: simon.egli+metapolator@gmail.com
  googlepluscommunity: https://plus.google.com/communities/110027004108709154749
